import Head from 'next/head'
import NavBar from '../_navbar'

export default function learn_index() {
    return (
        <div>
            <Head>
                <title>Выучить пайтон - легко!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar></NavBar>
            <main>
                <p>Learn index</p>
            </main>
        </div>
    )
}