import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function p1() {
    return (
        <div>
            <Head>
                <title>Знакомство с Пайтон!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <p>HEllo</p>
            </main>
        </div>
    )
}