import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Welcome to <text className={styles.code_string}>&quot;Hello, world&quot;</text></h1>

      <main>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="/projects" className={styles.card}>
            <h2>Projects &rarr;</h2>
            <p>See our projects</p>
          </a>

          <a href="/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn python on site</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Links &rarr;</h2>
            <p>Our projects's links</p>
          </a>
        </div>
      </main>
    </div>
  )
}
